import 'package:build/build.dart';

abstract class PackageBuilder extends Builder {
  @override
  Map<String, List<String>> get buildExtensions => throw new UnsupportedError(
      'PackageBuilder doesn\'t support buildExtensions');

  /// The relative paths from the package root to all the outputs that will be
  /// generated by this [PackageBuilder].
  Iterable<String> get outputs;
}

/// Converts `builder.outputs` to [AssetId]s under [package].
Iterable<AssetId> outputIdsForBuilder(PackageBuilder builder, String package) =>
    builder.outputs.map((path) => new AssetId(package, path));
