// dart format off
// Mocks generated by Mockito from annotations
// in mockito/example/build_extensions/example.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

import '../example.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [Dog].
///
/// See the documentation for Mockito's code generation for more information.
class MockDog extends _i1.Mock implements _i2.Dog {
  @override
  String sound() =>
      (super.noSuchMethod(
            Invocation.method(#sound, []),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#sound, []),
            ),
            returnValueForMissingStub: _i3.dummyValue<String>(
              this,
              Invocation.method(#sound, []),
            ),
          )
          as String);

  @override
  _i4.Future<void> chew() =>
      (super.noSuchMethod(
            Invocation.method(#chew, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
