name: build_workspace     # Can be anything
environment:
  sdk: ^3.7.0
publish_to: none
dev_dependencies:
  dart_flutter_team_lints: ^3.1.0

workspace:
- _benchmark
- build
- build_config
- build_daemon
- build_runner
- build_test
- builder_pkgs/build_modules
- builder_pkgs/build_modules/test/fixtures/a
- builder_pkgs/build_modules/test/fixtures/b
- builder_pkgs/build_web_compilers
- builder_pkgs/build_web_compilers/test/fixtures/c
- builder_pkgs/build_web_compilers/test/fixtures/d
- builder_pkgs/mockito
- builder_pkgs/scratch_space
- example
- tool
