name: build_workspace     # Can be anything
environment:
  sdk: ^3.7.0
publish_to: none
dev_dependencies:
  dart_flutter_team_lints: ^3.1.0

workspace:
- _benchmark
- build
- build_config
- build_daemon
- build_runner
- build_test
- builder_pkgs/build_modules
- builder_pkgs/build_modules/test/fixtures/a
- builder_pkgs/build_modules/test/fixtures/b
- builder_pkgs/build_web_compilers
- builder_pkgs/build_web_compilers/test/fixtures/c
- builder_pkgs/build_web_compilers/test/fixtures/d
- builder_pkgs/mockito
- builder_pkgs/scratch_space
- example
- tool

# Dependency overrides needed to resolve analyzer 13 pending releases of
# dart_style, source_gen, test_api and test_core.
dependency_overrides:
  analyzer: '13.0.0'
  dart_style:
    git:
      url: https://github.com/dart-lang/dart_style.git
      ref: c9975c66895011079bb3a98dc2271f4e038d45e8
  source_gen: '4.2.2'
  test_api:
    git:
      url: https://github.com/dart-lang/test.git
      ref: d0d5ccd037cb0eaea8e4dad900946ac54a4286c6
      path: pkgs/test_api
  test_core:
    git:
      url: https://github.com/dart-lang/test.git
      ref: d0d5ccd037cb0eaea8e4dad900946ac54a4286c6
      path: pkgs/test_core
