// dart format off
// Mocks generated by Mockito from annotations
// in mockito/test/end2end/dart_js_interop_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:js_interop' as _i1;

import 'package:mockito/mockito.dart' as _i2;
import 'package:mockito/src/dummies.dart' as _i4;

import 'uses_js_interop.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [UsesJSInterop].
///
/// See the documentation for Mockito's code generation for more information.
class MockUsesJSInterop<T extends _i1.JSAny> extends _i2.Mock
    implements _i3.UsesJSInterop<T> {
  MockUsesJSInterop() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i1.JSAny get jsAny =>
      (super.noSuchMethod(
            Invocation.getter(#jsAny),
            returnValue: _i4.dummyValue<_i1.JSAny>(
              this,
              Invocation.getter(#jsAny),
            ),
          )
          as _i1.JSAny);

  @override
  _i1.JSString get jsString =>
      (super.noSuchMethod(
            Invocation.getter(#jsString),
            returnValue: _i4.dummyValue<_i1.JSString>(
              this,
              Invocation.getter(#jsString),
            ),
          )
          as _i1.JSString);

  @override
  _i1.JSBoolean get jsBoolean =>
      (super.noSuchMethod(
            Invocation.getter(#jsBoolean),
            returnValue: _i4.dummyValue<_i1.JSBoolean>(
              this,
              Invocation.getter(#jsBoolean),
            ),
          )
          as _i1.JSBoolean);

  @override
  _i1.JSNumber get jsNumber =>
      (super.noSuchMethod(
            Invocation.getter(#jsNumber),
            returnValue: _i4.dummyValue<_i1.JSNumber>(
              this,
              Invocation.getter(#jsNumber),
            ),
          )
          as _i1.JSNumber);

  @override
  _i1.JSSymbol get jsSymbol =>
      (super.noSuchMethod(
            Invocation.getter(#jsSymbol),
            returnValue: _i4.dummyValue<_i1.JSSymbol>(
              this,
              Invocation.getter(#jsSymbol),
            ),
          )
          as _i1.JSSymbol);

  @override
  _i1.JSBigInt get jsBigInt =>
      (super.noSuchMethod(
            Invocation.getter(#jsBigInt),
            returnValue: _i4.dummyValue<_i1.JSBigInt>(
              this,
              Invocation.getter(#jsBigInt),
            ),
          )
          as _i1.JSBigInt);

  @override
  _i1.JSObject get jsObject =>
      (super.noSuchMethod(
            Invocation.getter(#jsObject),
            returnValue: _i4.dummyValue<_i1.JSObject>(
              this,
              Invocation.getter(#jsObject),
            ),
          )
          as _i1.JSObject);

  @override
  _i1.JSArray<_i1.JSAny?> get jsArray =>
      (super.noSuchMethod(
            Invocation.getter(#jsArray),
            returnValue: _i4.dummyValue<_i1.JSArray<_i1.JSAny?>>(
              this,
              Invocation.getter(#jsArray),
            ),
          )
          as _i1.JSArray<_i1.JSAny?>);

  @override
  _i1.JSFunction<Function> get jsFunction =>
      (super.noSuchMethod(
            Invocation.getter(#jsFunction),
            returnValue: _i4.dummyValue<_i1.JSFunction<Function>>(
              this,
              Invocation.getter(#jsFunction),
            ),
          )
          as _i1.JSFunction<Function>);

  @override
  _i1.JSDataView get jsDataView =>
      (super.noSuchMethod(
            Invocation.getter(#jsDataView),
            returnValue: _i4.dummyValue<_i1.JSDataView>(
              this,
              Invocation.getter(#jsDataView),
            ),
          )
          as _i1.JSDataView);

  @override
  _i1.JSArrayBuffer get jsArrayBuffer =>
      (super.noSuchMethod(
            Invocation.getter(#jsArrayBuffer),
            returnValue: _i4.dummyValue<_i1.JSArrayBuffer>(
              this,
              Invocation.getter(#jsArrayBuffer),
            ),
          )
          as _i1.JSArrayBuffer);

  @override
  _i1.JSTypedArray get jsTypedArray =>
      (super.noSuchMethod(
            Invocation.getter(#jsTypedArray),
            returnValue: _i4.dummyValue<_i1.JSTypedArray>(
              this,
              Invocation.getter(#jsTypedArray),
            ),
          )
          as _i1.JSTypedArray);

  @override
  _i1.JSInt8Array get jsInt8Array =>
      (super.noSuchMethod(
            Invocation.getter(#jsInt8Array),
            returnValue: _i4.dummyValue<_i1.JSInt8Array>(
              this,
              Invocation.getter(#jsInt8Array),
            ),
          )
          as _i1.JSInt8Array);

  @override
  _i1.JSUint8Array get jsUint8Array =>
      (super.noSuchMethod(
            Invocation.getter(#jsUint8Array),
            returnValue: _i4.dummyValue<_i1.JSUint8Array>(
              this,
              Invocation.getter(#jsUint8Array),
            ),
          )
          as _i1.JSUint8Array);

  @override
  _i1.JSUint8ClampedArray get jsUint8ClampedArray =>
      (super.noSuchMethod(
            Invocation.getter(#jsUint8ClampedArray),
            returnValue: _i4.dummyValue<_i1.JSUint8ClampedArray>(
              this,
              Invocation.getter(#jsUint8ClampedArray),
            ),
          )
          as _i1.JSUint8ClampedArray);

  @override
  _i1.JSInt16Array get jsInt16Array =>
      (super.noSuchMethod(
            Invocation.getter(#jsInt16Array),
            returnValue: _i4.dummyValue<_i1.JSInt16Array>(
              this,
              Invocation.getter(#jsInt16Array),
            ),
          )
          as _i1.JSInt16Array);

  @override
  _i1.JSUint16Array get jsUint16Array =>
      (super.noSuchMethod(
            Invocation.getter(#jsUint16Array),
            returnValue: _i4.dummyValue<_i1.JSUint16Array>(
              this,
              Invocation.getter(#jsUint16Array),
            ),
          )
          as _i1.JSUint16Array);

  @override
  _i1.JSInt32Array get jsInt32Array =>
      (super.noSuchMethod(
            Invocation.getter(#jsInt32Array),
            returnValue: _i4.dummyValue<_i1.JSInt32Array>(
              this,
              Invocation.getter(#jsInt32Array),
            ),
          )
          as _i1.JSInt32Array);

  @override
  _i1.JSUint32Array get jsUint32Array =>
      (super.noSuchMethod(
            Invocation.getter(#jsUint32Array),
            returnValue: _i4.dummyValue<_i1.JSUint32Array>(
              this,
              Invocation.getter(#jsUint32Array),
            ),
          )
          as _i1.JSUint32Array);

  @override
  _i1.JSFloat32Array get jsFloat32Array =>
      (super.noSuchMethod(
            Invocation.getter(#jsFloat32Array),
            returnValue: _i4.dummyValue<_i1.JSFloat32Array>(
              this,
              Invocation.getter(#jsFloat32Array),
            ),
          )
          as _i1.JSFloat32Array);

  @override
  _i1.JSFloat64Array get jsFloat64Array =>
      (super.noSuchMethod(
            Invocation.getter(#jsFloat64Array),
            returnValue: _i4.dummyValue<_i1.JSFloat64Array>(
              this,
              Invocation.getter(#jsFloat64Array),
            ),
          )
          as _i1.JSFloat64Array);

  @override
  _i3.UserInteropType get userInteropType =>
      (super.noSuchMethod(
            Invocation.getter(#userInteropType),
            returnValue: _i4.dummyValue<_i3.UserInteropType>(
              this,
              Invocation.getter(#userInteropType),
            ),
          )
          as _i3.UserInteropType);

  @override
  _i3.UserInteropTypeNested get userInteropTypeNested =>
      (super.noSuchMethod(
            Invocation.getter(#userInteropTypeNested),
            returnValue: _i4.dummyValue<_i3.UserInteropTypeNested>(
              this,
              Invocation.getter(#userInteropTypeNested),
            ),
          )
          as _i3.UserInteropTypeNested);

  @override
  T get t =>
      (super.noSuchMethod(
            Invocation.getter(#t),
            returnValue: _i4.dummyValue<T>(this, Invocation.getter(#t)),
          )
          as T);
}
