// Mocks generated by Mockito from annotations
// in mockito/test/end2end/generated_mocks_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

import 'foo.dart' as _i3;
import 'foo_sub.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFuture_0<T1> extends _i1.SmartFake implements _i2.Future<T1> {
  _FakeFuture_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBar_1 extends _i1.SmartFake implements _i3.Bar {
  _FakeBar_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Foo].
///
/// See the documentation for Mockito's code generation for more information.
class MockFoo<T> extends _i1.Mock implements _i3.Foo<T> {
  MockFoo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get getter =>
      (super.noSuchMethod(
            Invocation.getter(#getter),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#getter),
            ),
          )
          as String);

  @override
  set setter(int? value) => super.noSuchMethod(
    Invocation.setter(#setter, value),
    returnValueForMissingStub: null,
  );

  @override
  String positionalParameter(int? x) =>
      (super.noSuchMethod(
            Invocation.method(#positionalParameter, [x]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#positionalParameter, [x]),
            ),
          )
          as String);

  @override
  String namedParameter({required int? x}) =>
      (super.noSuchMethod(
            Invocation.method(#namedParameter, [], {#x: x}),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#namedParameter, [], {#x: x}),
            ),
          )
          as String);

  @override
  int operator +(int? arg) =>
      (super.noSuchMethod(Invocation.method(#+, [arg]), returnValue: 0) as int);

  @override
  String parameterWithDefault([int? x = 0]) =>
      (super.noSuchMethod(
            Invocation.method(#parameterWithDefault, [x]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#parameterWithDefault, [x]),
            ),
          )
          as String);

  @override
  String parameterWithDefault2([_i3.Foo<int>? x = const _i5.FooSub()]) =>
      (super.noSuchMethod(
            Invocation.method(#parameterWithDefault2, [x]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#parameterWithDefault2, [x]),
            ),
          )
          as String);

  @override
  String parameterWithDefaultFactoryRedirect([
    _i3.Foo<T>? x = const _i3.Foo.sub(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#parameterWithDefaultFactoryRedirect, [x]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#parameterWithDefaultFactoryRedirect, [x]),
            ),
          )
          as String);

  @override
  String? nullableMethod(int? x) =>
      (super.noSuchMethod(Invocation.method(#nullableMethod, [x])) as String?);

  @override
  String methodWithBarArg(_i3.Bar? bar) =>
      (super.noSuchMethod(
            Invocation.method(#methodWithBarArg, [bar]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#methodWithBarArg, [bar]),
            ),
          )
          as String);

  @override
  void returnsVoid() => super.noSuchMethod(
    Invocation.method(#returnsVoid, []),
    returnValueForMissingStub: null,
  );

  @override
  _i2.Future<void> returnsFutureVoid() =>
      (super.noSuchMethod(
            Invocation.method(#returnsFutureVoid, []),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void>? returnsNullableFutureVoid() =>
      (super.noSuchMethod(
            Invocation.method(#returnsNullableFutureVoid, []),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>?);

  @override
  _i2.Future<T> returnsFuture(T? x) =>
      (super.noSuchMethod(
            Invocation.method(#returnsFuture, [x]),
            returnValue:
                _i4.ifNotNull(
                  _i4.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#returnsFuture, [x]),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(this, Invocation.method(#returnsFuture, [x])),
          )
          as _i2.Future<T>);

  @override
  _i3.Bar returnsBar(int? arg) =>
      (super.noSuchMethod(
            Invocation.method(#returnsBar, [arg]),
            returnValue: _FakeBar_1(
              this,
              Invocation.method(#returnsBar, [arg]),
            ),
          )
          as _i3.Bar);

  @override
  String Function(int, [String]) returnsFunction() =>
      (super.noSuchMethod(
            Invocation.method(#returnsFunction, []),
            returnValue:
                (int x, [String? s]) => _i4.dummyValue<String>(
                  this,
                  Invocation.method(#returnsFunction, []),
                ),
          )
          as String Function(int, [String]));

  @override
  String Function(int, {String s}) returnsFunctionNamed() =>
      (super.noSuchMethod(
            Invocation.method(#returnsFunctionNamed, []),
            returnValue:
                (int x, {String? s}) => _i4.dummyValue<String>(
                  this,
                  Invocation.method(#returnsFunctionNamed, []),
                ),
          )
          as String Function(int, {String s}));
}

/// A class which mocks [FooSub].
///
/// See the documentation for Mockito's code generation for more information.
class MockFooSub extends _i1.Mock implements _i5.FooSub {
  MockFooSub() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get getter =>
      (super.noSuchMethod(
            Invocation.getter(#getter),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#getter),
            ),
          )
          as String);

  @override
  set setter(int? value) => super.noSuchMethod(
    Invocation.setter(#setter, value),
    returnValueForMissingStub: null,
  );

  @override
  String positionalParameter(int? x) =>
      (super.noSuchMethod(
            Invocation.method(#positionalParameter, [x]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#positionalParameter, [x]),
            ),
          )
          as String);

  @override
  String namedParameter({required int? x}) =>
      (super.noSuchMethod(
            Invocation.method(#namedParameter, [], {#x: x}),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#namedParameter, [], {#x: x}),
            ),
          )
          as String);

  @override
  int operator +(int? arg) =>
      (super.noSuchMethod(Invocation.method(#+, [arg]), returnValue: 0) as int);

  @override
  String parameterWithDefault([int? x = 0]) =>
      (super.noSuchMethod(
            Invocation.method(#parameterWithDefault, [x]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#parameterWithDefault, [x]),
            ),
          )
          as String);

  @override
  String parameterWithDefault2([_i3.Foo<int>? x = const _i5.FooSub()]) =>
      (super.noSuchMethod(
            Invocation.method(#parameterWithDefault2, [x]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#parameterWithDefault2, [x]),
            ),
          )
          as String);

  @override
  String parameterWithDefaultFactoryRedirect([
    _i3.Foo<int>? x = const _i3.Foo.sub(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#parameterWithDefaultFactoryRedirect, [x]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#parameterWithDefaultFactoryRedirect, [x]),
            ),
          )
          as String);

  @override
  String? nullableMethod(int? x) =>
      (super.noSuchMethod(Invocation.method(#nullableMethod, [x])) as String?);

  @override
  String methodWithBarArg(_i3.Bar? bar) =>
      (super.noSuchMethod(
            Invocation.method(#methodWithBarArg, [bar]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#methodWithBarArg, [bar]),
            ),
          )
          as String);

  @override
  void returnsVoid() => super.noSuchMethod(
    Invocation.method(#returnsVoid, []),
    returnValueForMissingStub: null,
  );

  @override
  _i2.Future<void> returnsFutureVoid() =>
      (super.noSuchMethod(
            Invocation.method(#returnsFutureVoid, []),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void>? returnsNullableFutureVoid() =>
      (super.noSuchMethod(
            Invocation.method(#returnsNullableFutureVoid, []),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>?);

  @override
  _i2.Future<int> returnsFuture(int? x) =>
      (super.noSuchMethod(
            Invocation.method(#returnsFuture, [x]),
            returnValue: _i2.Future<int>.value(0),
          )
          as _i2.Future<int>);

  @override
  _i3.Bar returnsBar(int? arg) =>
      (super.noSuchMethod(
            Invocation.method(#returnsBar, [arg]),
            returnValue: _FakeBar_1(
              this,
              Invocation.method(#returnsBar, [arg]),
            ),
          )
          as _i3.Bar);

  @override
  String Function(int, [String]) returnsFunction() =>
      (super.noSuchMethod(
            Invocation.method(#returnsFunction, []),
            returnValue:
                (int x, [String? s]) => _i4.dummyValue<String>(
                  this,
                  Invocation.method(#returnsFunction, []),
                ),
          )
          as String Function(int, [String]));

  @override
  String Function(int, {String s}) returnsFunctionNamed() =>
      (super.noSuchMethod(
            Invocation.method(#returnsFunctionNamed, []),
            returnValue:
                (int x, {String? s}) => _i4.dummyValue<String>(
                  this,
                  Invocation.method(#returnsFunctionNamed, []),
                ),
          )
          as String Function(int, {String s}));
}

/// A class which mocks [Bar].
///
/// See the documentation for Mockito's code generation for more information.
class MockBar extends _i1.Mock implements _i3.Bar {
  MockBar() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get x =>
      (super.noSuchMethod(Invocation.getter(#x), returnValue: 0) as int);

  @override
  int f() =>
      (super.noSuchMethod(Invocation.method(#f, []), returnValue: 0) as int);
}

/// A class which mocks [Foo].
///
/// See the documentation for Mockito's code generation for more information.
class MockFooWithDefaults<T> extends _i1.Mock implements _i3.Foo<T> {
  @override
  String get getter =>
      (super.noSuchMethod(
            Invocation.getter(#getter),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#getter),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.getter(#getter),
            ),
          )
          as String);

  @override
  set setter(int? value) => super.noSuchMethod(
    Invocation.setter(#setter, value),
    returnValueForMissingStub: null,
  );

  @override
  String positionalParameter(int? x) =>
      (super.noSuchMethod(
            Invocation.method(#positionalParameter, [x]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#positionalParameter, [x]),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.method(#positionalParameter, [x]),
            ),
          )
          as String);

  @override
  String namedParameter({required int? x}) =>
      (super.noSuchMethod(
            Invocation.method(#namedParameter, [], {#x: x}),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#namedParameter, [], {#x: x}),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.method(#namedParameter, [], {#x: x}),
            ),
          )
          as String);

  @override
  int operator +(int? arg) =>
      (super.noSuchMethod(
            Invocation.method(#+, [arg]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  String parameterWithDefault([int? x = 0]) =>
      (super.noSuchMethod(
            Invocation.method(#parameterWithDefault, [x]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#parameterWithDefault, [x]),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.method(#parameterWithDefault, [x]),
            ),
          )
          as String);

  @override
  String parameterWithDefault2([_i3.Foo<int>? x = const _i5.FooSub()]) =>
      (super.noSuchMethod(
            Invocation.method(#parameterWithDefault2, [x]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#parameterWithDefault2, [x]),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.method(#parameterWithDefault2, [x]),
            ),
          )
          as String);

  @override
  String parameterWithDefaultFactoryRedirect([
    _i3.Foo<T>? x = const _i3.Foo.sub(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#parameterWithDefaultFactoryRedirect, [x]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#parameterWithDefaultFactoryRedirect, [x]),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.method(#parameterWithDefaultFactoryRedirect, [x]),
            ),
          )
          as String);

  @override
  String? nullableMethod(int? x) =>
      (super.noSuchMethod(
            Invocation.method(#nullableMethod, [x]),
            returnValueForMissingStub: null,
          )
          as String?);

  @override
  String methodWithBarArg(_i3.Bar? bar) =>
      (super.noSuchMethod(
            Invocation.method(#methodWithBarArg, [bar]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#methodWithBarArg, [bar]),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.method(#methodWithBarArg, [bar]),
            ),
          )
          as String);

  @override
  void returnsVoid() => super.noSuchMethod(
    Invocation.method(#returnsVoid, []),
    returnValueForMissingStub: null,
  );

  @override
  _i2.Future<void> returnsFutureVoid() =>
      (super.noSuchMethod(
            Invocation.method(#returnsFutureVoid, []),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void>? returnsNullableFutureVoid() =>
      (super.noSuchMethod(
            Invocation.method(#returnsNullableFutureVoid, []),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>?);

  @override
  _i2.Future<T> returnsFuture(T? x) =>
      (super.noSuchMethod(
            Invocation.method(#returnsFuture, [x]),
            returnValue:
                _i4.ifNotNull(
                  _i4.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#returnsFuture, [x]),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(this, Invocation.method(#returnsFuture, [x])),
            returnValueForMissingStub:
                _i4.ifNotNull(
                  _i4.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#returnsFuture, [x]),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(this, Invocation.method(#returnsFuture, [x])),
          )
          as _i2.Future<T>);

  @override
  _i3.Bar returnsBar(int? arg) =>
      (super.noSuchMethod(
            Invocation.method(#returnsBar, [arg]),
            returnValue: _FakeBar_1(
              this,
              Invocation.method(#returnsBar, [arg]),
            ),
            returnValueForMissingStub: _FakeBar_1(
              this,
              Invocation.method(#returnsBar, [arg]),
            ),
          )
          as _i3.Bar);

  @override
  String Function(int, [String]) returnsFunction() =>
      (super.noSuchMethod(
            Invocation.method(#returnsFunction, []),
            returnValue:
                (int x, [String? s]) => _i4.dummyValue<String>(
                  this,
                  Invocation.method(#returnsFunction, []),
                ),
            returnValueForMissingStub:
                (int x, [String? s]) => _i4.dummyValue<String>(
                  this,
                  Invocation.method(#returnsFunction, []),
                ),
          )
          as String Function(int, [String]));

  @override
  String Function(int, {String s}) returnsFunctionNamed() =>
      (super.noSuchMethod(
            Invocation.method(#returnsFunctionNamed, []),
            returnValue:
                (int x, {String? s}) => _i4.dummyValue<String>(
                  this,
                  Invocation.method(#returnsFunctionNamed, []),
                ),
            returnValueForMissingStub:
                (int x, {String? s}) => _i4.dummyValue<String>(
                  this,
                  Invocation.method(#returnsFunctionNamed, []),
                ),
          )
          as String Function(int, {String s}));
}

/// A class which mocks [Baz].
///
/// See the documentation for Mockito's code generation for more information.
class MockBazWithUnsupportedMembers<S> extends _i1.Mock implements _i3.Baz<S> {
  MockBazWithUnsupportedMembers() {
    _i1.throwOnMissingStub(this);
  }

  @override
  S get typeVariableField =>
      (super.noSuchMethod(
            Invocation.getter(#typeVariableField),
            returnValue: _i4.dummyValue<S>(
              this,
              Invocation.getter(#typeVariableField),
            ),
          )
          as S);

  @override
  get privateTypeField =>
      throw UnsupportedError(
        r'"privateTypeField" cannot be used without a mockito fallback generator.',
      );

  @override
  T returnsTypeVariable<T>() =>
      (super.noSuchMethod(
            Invocation.method(#returnsTypeVariable, []),
            returnValue: _i4.dummyValue<T>(
              this,
              Invocation.method(#returnsTypeVariable, []),
            ),
          )
          as T);

  @override
  T returnsBoundedTypeVariable<T extends num?>() =>
      (super.noSuchMethod(
            Invocation.method(#returnsBoundedTypeVariable, []),
            returnValue: _i4.dummyValue<T>(
              this,
              Invocation.method(#returnsBoundedTypeVariable, []),
            ),
          )
          as T);

  @override
  T returnsTypeVariableFromTwo<T, U>() =>
      (super.noSuchMethod(
            Invocation.method(#returnsTypeVariableFromTwo, []),
            returnValue: _i4.dummyValue<T>(
              this,
              Invocation.method(#returnsTypeVariableFromTwo, []),
            ),
          )
          as T);

  @override
  S Function(S) returnsGenericFunction() =>
      (super.noSuchMethod(
            Invocation.method(#returnsGenericFunction, []),
            returnValue:
                (S __p0) => _i4.dummyValue<S>(
                  this,
                  Invocation.method(#returnsGenericFunction, []),
                ),
          )
          as S Function(S));

  @override
  returnsPrivate() =>
      throw UnsupportedError(
        r'"returnsPrivate" cannot be used without a mockito fallback generator.',
      );

  @override
  void privateArg(arg) =>
      throw UnsupportedError(
        r'"privateArg" cannot be used without a mockito fallback generator.',
      );

  @override
  $hasDollarInName() =>
      throw UnsupportedError(
        r'"$hasDollarInName" cannot be used without a mockito fallback generator.',
      );
}

/// A class which mocks [HasPrivate].
///
/// See the documentation for Mockito's code generation for more information.
class MockHasPrivate extends _i1.Mock
    with _i3.HasPrivateMixin
    implements _i3.HasPrivate {
  MockHasPrivate() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [Foo].
///
/// See the documentation for Mockito's code generation for more information.
class MockFooNice<T> extends _i1.Mock implements _i3.Foo<T> {
  @override
  String get getter =>
      (super.noSuchMethod(
            Invocation.getter(#getter),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#getter),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.getter(#getter),
            ),
          )
          as String);

  @override
  set setter(int? value) => super.noSuchMethod(
    Invocation.setter(#setter, value),
    returnValueForMissingStub: null,
  );

  @override
  String positionalParameter(int? x) =>
      (super.noSuchMethod(
            Invocation.method(#positionalParameter, [x]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#positionalParameter, [x]),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.method(#positionalParameter, [x]),
            ),
          )
          as String);

  @override
  String namedParameter({required int? x}) =>
      (super.noSuchMethod(
            Invocation.method(#namedParameter, [], {#x: x}),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#namedParameter, [], {#x: x}),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.method(#namedParameter, [], {#x: x}),
            ),
          )
          as String);

  @override
  int operator +(int? arg) =>
      (super.noSuchMethod(
            Invocation.method(#+, [arg]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  String parameterWithDefault([int? x = 0]) =>
      (super.noSuchMethod(
            Invocation.method(#parameterWithDefault, [x]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#parameterWithDefault, [x]),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.method(#parameterWithDefault, [x]),
            ),
          )
          as String);

  @override
  String parameterWithDefault2([_i3.Foo<int>? x = const _i5.FooSub()]) =>
      (super.noSuchMethod(
            Invocation.method(#parameterWithDefault2, [x]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#parameterWithDefault2, [x]),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.method(#parameterWithDefault2, [x]),
            ),
          )
          as String);

  @override
  String parameterWithDefaultFactoryRedirect([
    _i3.Foo<T>? x = const _i3.Foo.sub(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#parameterWithDefaultFactoryRedirect, [x]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#parameterWithDefaultFactoryRedirect, [x]),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.method(#parameterWithDefaultFactoryRedirect, [x]),
            ),
          )
          as String);

  @override
  String? nullableMethod(int? x) =>
      (super.noSuchMethod(
            Invocation.method(#nullableMethod, [x]),
            returnValueForMissingStub: null,
          )
          as String?);

  @override
  String methodWithBarArg(_i3.Bar? bar) =>
      (super.noSuchMethod(
            Invocation.method(#methodWithBarArg, [bar]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#methodWithBarArg, [bar]),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.method(#methodWithBarArg, [bar]),
            ),
          )
          as String);

  @override
  void returnsVoid() => super.noSuchMethod(
    Invocation.method(#returnsVoid, []),
    returnValueForMissingStub: null,
  );

  @override
  _i2.Future<void> returnsFutureVoid() =>
      (super.noSuchMethod(
            Invocation.method(#returnsFutureVoid, []),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void>? returnsNullableFutureVoid() =>
      (super.noSuchMethod(
            Invocation.method(#returnsNullableFutureVoid, []),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>?);

  @override
  _i2.Future<T> returnsFuture(T? x) =>
      (super.noSuchMethod(
            Invocation.method(#returnsFuture, [x]),
            returnValue:
                _i4.ifNotNull(
                  _i4.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#returnsFuture, [x]),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(this, Invocation.method(#returnsFuture, [x])),
            returnValueForMissingStub:
                _i4.ifNotNull(
                  _i4.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#returnsFuture, [x]),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(this, Invocation.method(#returnsFuture, [x])),
          )
          as _i2.Future<T>);

  @override
  _i3.Bar returnsBar(int? arg) =>
      (super.noSuchMethod(
            Invocation.method(#returnsBar, [arg]),
            returnValue: _FakeBar_1(
              this,
              Invocation.method(#returnsBar, [arg]),
            ),
            returnValueForMissingStub: _FakeBar_1(
              this,
              Invocation.method(#returnsBar, [arg]),
            ),
          )
          as _i3.Bar);

  @override
  String Function(int, [String]) returnsFunction() =>
      (super.noSuchMethod(
            Invocation.method(#returnsFunction, []),
            returnValue:
                (int x, [String? s]) => _i4.dummyValue<String>(
                  this,
                  Invocation.method(#returnsFunction, []),
                ),
            returnValueForMissingStub:
                (int x, [String? s]) => _i4.dummyValue<String>(
                  this,
                  Invocation.method(#returnsFunction, []),
                ),
          )
          as String Function(int, [String]));

  @override
  String Function(int, {String s}) returnsFunctionNamed() =>
      (super.noSuchMethod(
            Invocation.method(#returnsFunctionNamed, []),
            returnValue:
                (int x, {String? s}) => _i4.dummyValue<String>(
                  this,
                  Invocation.method(#returnsFunctionNamed, []),
                ),
            returnValueForMissingStub:
                (int x, {String? s}) => _i4.dummyValue<String>(
                  this,
                  Invocation.method(#returnsFunctionNamed, []),
                ),
          )
          as String Function(int, {String s}));
}

/// A class which mocks [Bar].
///
/// See the documentation for Mockito's code generation for more information.
class MockBarNice extends _i1.Mock implements _i3.Bar {
  @override
  int get x =>
      (super.noSuchMethod(
            Invocation.getter(#x),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int f() =>
      (super.noSuchMethod(
            Invocation.method(#f, []),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);
}

/// A class which mocks [UsesExtTypes].
///
/// See the documentation for Mockito's code generation for more information.
class MockUsesExtTypes extends _i1.Mock implements _i3.UsesExtTypes {
  @override
  bool extTypeArg(_i3.Ext? _0) =>
      (super.noSuchMethod(
            Invocation.method(#extTypeArg, [_0]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.Ext extTypeReturn(int? _0) =>
      (super.noSuchMethod(
            Invocation.method(#extTypeReturn, [_0]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as _i3.Ext);

  @override
  bool privateExtTypeArg(_i3.ExtOfPrivate? _0) =>
      (super.noSuchMethod(
            Invocation.method(#privateExtTypeArg, [_0]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.ExtOfPrivate privateExtTypeReturn(int? _0) =>
      (super.noSuchMethod(
            Invocation.method(#privateExtTypeReturn, [_0]),
            returnValue: _i4.dummyValue<_i3.ExtOfPrivate>(
              this,
              Invocation.method(#privateExtTypeReturn, [_0]),
            ),
            returnValueForMissingStub: _i4.dummyValue<_i3.ExtOfPrivate>(
              this,
              Invocation.method(#privateExtTypeReturn, [_0]),
            ),
          )
          as _i3.ExtOfPrivate);
}
