// dart format off
// Mocks generated by Mockito from annotations
// in mockito/example/example.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;

import 'example.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCat_0 extends _i1.SmartFake implements _i2.Cat {
  _FakeCat_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Cat].
///
/// See the documentation for Mockito's code generation for more information.
class MockCat extends _i1.Mock implements _i2.Cat {
  MockCat() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get lives =>
      (super.noSuchMethod(Invocation.getter(#lives), returnValue: 0) as int);

  @override
  set lives(int? value) => super.noSuchMethod(
    Invocation.setter(#lives, value),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> chew() =>
      (super.noSuchMethod(
            Invocation.method(#chew, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void sleep() => super.noSuchMethod(
    Invocation.method(#sleep, []),
    returnValueForMissingStub: null,
  );

  @override
  void hunt(String? place, String? prey) => super.noSuchMethod(
    Invocation.method(#hunt, [place, prey]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [Callbacks].
///
/// See the documentation for Mockito's code generation for more information.
class MockCallbacks extends _i1.Mock implements _i2.Callbacks {
  MockCallbacks() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Cat findCat(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#findCat, [name]),
            returnValue: _FakeCat_0(this, Invocation.method(#findCat, [name])),
          )
          as _i2.Cat);
}

/// A class which mocks [Cat].
///
/// See the documentation for Mockito's code generation for more information.
class MockCatRelaxed extends _i1.Mock implements _i2.Cat {
  @override
  int get lives =>
      (super.noSuchMethod(
            Invocation.getter(#lives),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  set lives(int? value) => super.noSuchMethod(
    Invocation.setter(#lives, value),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> chew() =>
      (super.noSuchMethod(
            Invocation.method(#chew, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void sleep() => super.noSuchMethod(
    Invocation.method(#sleep, []),
    returnValueForMissingStub: null,
  );

  @override
  void hunt(String? place, String? prey) => super.noSuchMethod(
    Invocation.method(#hunt, [place, prey]),
    returnValueForMissingStub: null,
  );
}
