name: Build

on:
  schedule:
    # “At 00:00 (UTC) on Sunday.”
    - cron: '0 0 * * 0'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: dart-lang/setup-dart@6afc89df92d6eb3834022f73cd65adc8cdfcb92d

      - name: Install dependencies
        run: |
          dart pub get
          (cd benchmark; dart pub get)
  
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze --fatal-infos

      - name: Run tests
        run: dart test
