// Copyright (c) 2025, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'package:build/build.dart' hide Builder;
import 'package:built_collection/built_collection.dart';
import 'package:built_value/built_value.dart';

import '../build/asset_content.dart';
import '../build/br_outputs.dart';
import '../build/build_state/finished_build_state.dart';
import '../build/library_cycle_graph/phased_asset_deps.dart';
import '../constants.dart';
import '../exceptions.dart';
import '../io/asset_tracker.dart';
import '../io/reader_writer.dart';
import '../logging/build_log.dart';
import 'asset_file.dart';
import 'build_directory.dart';
import 'build_filter.dart';
import 'build_inputs.dart';
import 'build_spec.dart';
import 'build_step_plan.dart';
import 'output_strategy.dart';
import 'previous_build.dart';

part 'build_plan.g.dart';

/// Options and derived configuration for a build.
abstract class BuildPlan implements Built<BuildPlan, BuildPlanBuilder> {
  BuildSpec get buildSpec;
  PreviousBuild get previousBuild;
  BuildStepPlan get buildStepPlan;
  ReaderWriter get readerWriter => buildSpec.readerWriter;

  /// Callback that gets notified of deletes.

  /// Files on disk that conflict with declared outputs and must be deleted.
  BuiltList<AssetFile> get conflictingOutputs;

  /// Sources and changes to sources before the build.
  BuildInputs get buildInputs;

  /// Per-build build dirs, which can differ from the global option in
  /// `BuildOptions`.
  BuiltSet<BuildDirectory> get buildDirs;

  /// Per-build build filters, which can differ from the global option in
  /// `BuildOptions`.
  BuiltSet<BuildFilter> get buildFilters;

  BuildPlan._();
  factory BuildPlan([void Function(BuildPlanBuilder) updates]) = _$BuildPlan;

  /// Loads the build plan for [buildSpec].
  ///
  /// Loads information about the previous build as [previousBuild].
  ///
  /// Files that should be deleted before restarting or building are tracked.
  ///
  /// [buildInputs] are resolved.
  static Future<BuildPlan> load(BuildSpec buildSpec) async {
    final previousBuild = await PreviousBuild.load(buildSpec);
    final buildPackages = buildSpec.buildPackages;

    // Find sources on disk.
    final assetTracker = AssetTracker(
      buildSpec.readerWriter,
      buildPackages,
      buildSpec.buildConfigs,
    );
    final diskFiles = await assetTracker.findFiles();

    final hasCompatiblePreviousBuild = previousBuild.incrementalState != null;
    if (!hasCompatiblePreviousBuild) {
      // If there is no compatible previous build, compute inputs with files
      // that look like old generation outputs removed.

      final inputSources = diskFiles
          .where((f) => f.atPackagePath)
          .map((f) => f.id)
          .toSet();

      // Remove files from the incompatible build.
      inputSources.removeAll(previousBuild.incompatibleBuildOutputsToDelete);
      // The asset graph JSON is not an input.
      inputSources.remove(
        AssetId(buildPackages.outputRoot, assetGraphJsonPath),
      );

      // Remove from inputs files that will be generated by the current build.
      final declaredOutputs = BuildStepPlan.compute(
        buildPhases: buildSpec.buildPhases,
        placeholderIds: buildPackages.placeholderIds,
        sources: inputSources,
      ).declaredOutputs;
      inputSources.removeAll(declaredOutputs);

      return _createClean(
        buildSpec: buildSpec,
        previousBuild: previousBuild,
        buildDirs: buildSpec.buildOptions.buildDirs,
        buildFilters: buildSpec.buildOptions.buildFilters,
        filesToCheck: inputSources.map(AssetFile.atPackagePath).toSet(),
        diskFiles: diskFiles,
      );
    } else {
      // If there is a compatible previous build, check all previous build files
      // and all discovered files on disk.
      final filesToCheck = <AssetFile>{
        ...diskFiles,
        ...previousBuild.sources.map(AssetFile.atPackagePath),
        ...previousBuild.actualOutputs.map(
          (id) =>
              AssetFile(id, inArtifactTree: previousBuild.isInArtifactTree(id)),
        ),
        ...previousBuild.actualPostOutputs.map(
          (id) =>
              AssetFile(id, inArtifactTree: previousBuild.isInArtifactTree(id)),
        ),
        ...previousBuild.sharedPartIds.map(AssetFile.atPackagePath),
      };

      final previousBuildStepPlan = previousBuild.buildStepPlan!;

      return _createIncremental(
        buildSpec: buildSpec,
        previousBuild: previousBuild,
        previousBuildStepPlan: previousBuildStepPlan,
        buildDirs: buildSpec.buildOptions.buildDirs,
        buildFilters: buildSpec.buildOptions.buildFilters,
        filesToCheck: filesToCheck,
      );
    }
  }

  /// Returns a copy of the plan with [previousBuild] updated for the next
  /// incremental build.
  BuildPlan withCompatiblePreviousBuild({
    required FinishedBuildState previousBuildState,
    required PhasedAssetDeps previousPhasedAssetDeps,
  }) => rebuild(
    (b) => b
      ..previousBuild.replace(
        previousBuild.updateForNextBuild(
          previousPhasedAssetDeps: previousPhasedAssetDeps,
          finishedBuildState: previousBuildState,
        ),
      )
      ..buildInputs.cleanBuild = false
      ..buildInputs.sourceContents.clear()
      ..buildInputs.sourceContents.addEntries(previousBuildState.sourceContents)
      ..buildInputs.retainedOutputContents.clear()
      ..buildInputs.retainedOutputContents.addEntries(
        previousBuildState.outputContents,
      )
      ..buildInputs.deletedSources.clear()
      ..buildInputs.updatedSources.clear()
      ..buildInputs.invalidOutputs.clear()
      ..conflictingOutputs.clear(),
  );

  Future<BuildPlan> updateForFileChanges(Set<AssetFile> filesToCheck) {
    if (previousBuild.incrementalState == null) {
      return _createClean(
        buildSpec: buildSpec,
        previousBuild: previousBuild,
        buildDirs: buildDirs,
        buildFilters: buildFilters,
        filesToCheck: filesToCheck,
        // Updates are being made to a `BuildPlan` that didn't actually run.
        // That means the conflicting file check was already done when that
        // `BuildPlan` was created, don't repeat it.
        diskFiles: null,
      );
    } else {
      return _createIncremental(
        buildSpec: buildSpec,
        previousBuild: previousBuild,
        previousBuildStepPlan: buildStepPlan,
        previousBuildInputs: buildInputs,
        buildDirs: buildDirs,
        buildFilters: buildFilters,
        filesToCheck: filesToCheck,
      );
    }
  }

  /// Whether [phaseNumber] has different options to the previous build
  /// and must be fully rebuilt.
  bool phaseOptionsChanged(int phaseNumber) =>
      previousBuild.phaseOptionsChangedList[phaseNumber];

  /// Whether [actionNumber] has different options to the previous build
  /// and must be fully rebuilt.
  bool postBuildOptionsChanged(int actionNumber) =>
      previousBuild.postBuildOptionsChangedList[actionNumber];

  /// Creates a [BuildPlan] for a clean build.
  ///
  /// Pass [diskFiles] to check if any files that builders will generate
  /// conflict with files already on disk. Conflicts in dependencies cause an
  /// exception to be thrown, conflicts in writable packages are added to
  /// [conflictingOutputs] so they will be deleted.
  static Future<BuildPlan> _createClean({
    required BuildSpec buildSpec,
    required PreviousBuild previousBuild,
    required BuiltSet<BuildDirectory> buildDirs,
    required BuiltSet<BuildFilter> buildFilters,
    required Set<AssetFile> filesToCheck,
    Set<AssetFile>? diskFiles,
  }) async {
    final readerWriter = buildSpec.readerWriter;
    final result = BuildInputsBuilder()..cleanBuild = true;

    for (final file in filesToCheck) {
      if (file.inArtifactTree) continue;
      if (await readerWriter.canRead(file.id)) {
        result.sources.add(file.id);
      }
    }

    final buildStepPlan = BuildStepPlan.compute(
      buildPhases: buildSpec.buildPhases,
      placeholderIds: buildSpec.buildPackages.placeholderIds,
      sources: result.sources.build(),
    );

    final conflictingOutputs = <AssetFile>{};
    final buildPackages = buildSpec.buildPackages;

    if (diskFiles != null) {
      final conflictsInDeps = buildStepPlan.declaredOutputs
          .where((n) => !buildPackages.outputPackages.contains(n.package))
          .where((n) => diskFiles.contains(AssetFile.atPackagePath(n)))
          .toSet();
      if (conflictsInDeps.isNotEmpty) {
        buildLog.error(
          'There are existing files in dependencies which conflict '
          'with files that a Builder may produce. These must be removed or '
          'the Builders disabled before a build can continue: '
          '${conflictsInDeps.map((a) => a.uri).join('\n')}',
        );
        throw const CannotBuildException();
      }

      for (final file in diskFiles) {
        if (buildStepPlan.isDeclaredOutput(file.id)) {
          if (file.atPackagePath &&
              buildPackages.outputPackages.contains(file.id.package)) {
            conflictingOutputs.add(file);
          } else if (file.inArtifactTree &&
              buildStepPlan.isDeclaredOutputAtPackagePath(file.id)) {
            conflictingOutputs.add(file);
          }
        }
      }
    }

    for (final id in result.sources.build()) {
      if (buildStepPlan.declaredOutputsOf(id).isNotEmpty) {
        try {
          result.sourceContents[id] = AssetContent.bytes(
            await readerWriter.readAsBytes(id),
          );
        } catch (_) {}
      }
    }

    return BuildPlan((b) {
      b.buildSpec.replace(buildSpec);
      b.previousBuild.replace(previousBuild);
      b.buildStepPlan.replace(buildStepPlan);
      b.conflictingOutputs.replace(conflictingOutputs);
      b.buildInputs.replace(result.build());
      b.buildDirs.replace(buildDirs);
      b.buildFilters.replace(buildFilters);
    });
  }

  /// Creates a [BuildPlan] for an incremental build.
  static Future<BuildPlan> _createIncremental({
    required BuildSpec buildSpec,
    required PreviousBuild previousBuild,
    required BuildStepPlan previousBuildStepPlan,
    BuildInputs? previousBuildInputs,
    required BuiltSet<BuildDirectory> buildDirs,
    required BuiltSet<BuildFilter> buildFilters,
    required Set<AssetFile> filesToCheck,
  }) async {
    final readerWriter = buildSpec.readerWriter;
    final buildInputs = BuildInputsBuilder()..cleanBuild = false;
    if (previousBuildInputs != null) {
      buildInputs.sourceContents.replace(previousBuildInputs.sourceContents);
      buildInputs.retainedOutputContents.replace(
        previousBuildInputs.retainedOutputContents,
      );
    }

    var buildStepPlan = previousBuildStepPlan;

    buildInputs.sources.addAll(previousBuild.sources);

    final conflictingOutputs = <AssetFile>{};
    final newArtifactTreeFiles = <AssetId>{};

    for (final file in filesToCheck) {
      final id = file.id;
      final oldIsSource = previousBuild.isSource(id);
      AssetFile? oldFile;
      if (oldIsSource) {
        oldFile = AssetFile.atPackagePath(id);
      } else if (id.isBrOutput && previousBuild.hasSharedPart(id)) {
        oldFile = AssetFile.atPackagePath(id);
      } else if (previousBuild.isActualOutput(id) ||
          previousBuild.isActualPostOutput(id)) {
        oldFile = AssetFile(
          id,
          inArtifactTree: previousBuild.isInArtifactTree(id),
        );
      }
      final oldExistedSameLocation = oldFile == file;
      final oldDigest = oldExistedSameLocation
          ? previousBuild.digestOf(id)
          : null;

      var exists = false;
      AssetContent? newContent;
      if (await readerWriter.canRead(id, inArtifactTree: file.inArtifactTree)) {
        exists = true;
        if (oldDigest != null) {
          try {
            final bytes = await readerWriter.readAsBytes(
              id,
              inArtifactTree: file.inArtifactTree,
            );
            newContent = AssetContent.bytes(bytes);
          } catch (_) {
            exists = false;
          }
        }
      }

      if (!exists) {
        if (oldExistedSameLocation) {
          if (oldIsSource) {
            buildInputs.deletedSources.add(id);
            buildInputs.sources.remove(id);
            buildInputs.sourceContents.remove(id);
          } else {
            buildInputs.retainedOutputContents.remove(id);
            buildInputs.invalidOutputs.add(id);
          }
        }
        continue;
      }

      if (!oldExistedSameLocation) {
        if (file.inArtifactTree) {
          newArtifactTreeFiles.add(id);
          conflictingOutputs.add(file);
        } else if (id.isBrOutput) {
          conflictingOutputs.add(file);
        } else {
          buildInputs.updatedSources.add(id);
          buildInputs.sources.add(id);
        }
        continue;
      }

      if (newContent == null) continue;

      final changed = oldDigest != newContent.digest;

      if (oldIsSource) {
        if (changed) buildInputs.updatedSources.add(id);
        buildInputs.sourceContents[id] = newContent;
        continue;
      }

      if (id.isBrOutput) {
        final libraryId = id.sharedPartLibraryId;
        final existing = libraryId != null
            ? previousBuild.sharedPartOrNull(libraryId)
            : null;
        if (existing != null) {
          if (buildSpec.buildOptions.outputStrategy == OutputStrategy.keep) {
            buildInputs.retainedOutputContents[id] = AssetContent.bytes(
              newContent.bytes,
              digest: oldDigest,
            );
          } else if (changed) {
            buildInputs.invalidOutputs.add(id);
          } else {
            buildInputs.retainedOutputContents[id] = newContent;
          }
        } else {
          buildInputs.invalidOutputs.add(id);
        }
        continue;
      }

      if (!changed) {
        // It's an output of the previous build that has remained unchanged on
        // disk. Store it as `retainedOutputContents` so the next build can
        // reuse it if it decides it does not need to be rebuilt.
        buildInputs.retainedOutputContents[id] = newContent;
        continue;
      }

      if (buildSpec.buildOptions.outputStrategy == OutputStrategy.keep) {
        // `--keep` mode retains external modifications to outputs as if the
        // content matches: copy the old digest.
        buildInputs.retainedOutputContents[id] = AssetContent.bytes(
          newContent.bytes,
          digest: oldDigest,
        );
      } else {
        buildInputs.retainedOutputContents.remove(id);
        buildInputs.invalidOutputs.add(id);
      }
    }

    buildStepPlan = BuildStepPlan.compute(
      buildPhases: buildSpec.buildPhases,
      placeholderIds: buildSpec.buildPackages.placeholderIds,
      sources: buildInputs.sources.build(),
    );

    final declaredOutputs = buildStepPlan.declaredOutputs;
    final currentSources = buildInputs.sources.build();
    final postBuildActions =
        buildSpec.buildPhases.postBuildPhase.builderActions;
    // Outputs that were misclassified as sources.
    final misclassifiedSources = <AssetId>{};
    for (final id in currentSources) {
      if (declaredOutputs.contains(id)) {
        misclassifiedSources.add(id);
      } else {
        final postStepId = previousBuild.postProcessOutputs[id];
        if (postStepId != null) {
          final producingInput = postStepId.input;
          final inputExists =
              currentSources.contains(producingInput) ||
              buildStepPlan.isDeclaredOutput(producingInput);
          if (inputExists &&
              postStepId.actionNumber < postBuildActions.length &&
              buildStepPlan.actionMatches(
                postBuildActions[postStepId.actionNumber],
                producingInput,
              )) {
            misclassifiedSources.add(id);
          }
        }
      }
    }
    if (misclassifiedSources.isNotEmpty) {
      final buildPackages = buildSpec.buildPackages;
      final conflictsInDeps = misclassifiedSources
          .where((n) => !buildPackages.outputPackages.contains(n.package))
          .toSet();
      if (conflictsInDeps.isNotEmpty) {
        buildLog.error(
          'There are existing files in dependencies which conflict '
          'with files that a Builder may produce. These must be removed or '
          'the Builders disabled before a build can continue: '
          '${conflictsInDeps.map((a) => a.uri).join('\n')}',
        );
        throw const CannotBuildException();
      }

      buildInputs.sources.removeAll(misclassifiedSources);
      buildInputs.sourceContents.removeWhere(
        (id, _) => misclassifiedSources.contains(id),
      );
      buildInputs.updatedSources.removeWhere(misclassifiedSources.contains);
      for (final id in misclassifiedSources) {
        conflictingOutputs.add(AssetFile.atPackagePath(id));
      }
      buildStepPlan = BuildStepPlan.compute(
        buildPhases: buildSpec.buildPhases,
        placeholderIds: buildSpec.buildPackages.placeholderIds,
        sources: buildInputs.sources.build(),
      );
    }

    final finalSources = buildInputs.sources.build();
    for (final id in finalSources) {
      buildInputs.retainedOutputContents.remove(id);
    }
    for (final id in newArtifactTreeFiles) {
      if (!finalSources.contains(id) &&
          buildInputs.retainedOutputContents[id] == null) {
        buildInputs.invalidOutputs.add(id);
      }
    }

    for (final id in finalSources) {
      if (buildInputs.sourceContents[id] == null &&
          buildStepPlan.declaredOutputsOf(id).isNotEmpty) {
        try {
          final bytes = await readerWriter.readAsBytes(
            id,
            inArtifactTree: buildStepPlan.isDeclaredOutputInArtifactTree(id),
          );
          final content = AssetContent.bytes(bytes);
          buildInputs.sourceContents[id] = content;
        } catch (_) {}
      }
    }

    final invalidOutputs = previousBuildStepPlan
        .transitiveDeclaredOutputsOf(buildInputs.deletedSources.build())
        .toSet();
    buildInputs.invalidOutputs.addAll(invalidOutputs);
    buildInputs.invalidOutputs.removeAll(finalSources);
    for (final invalid in invalidOutputs) {
      buildInputs.retainedOutputContents.remove(invalid);
    }

    return BuildPlan((b) {
      b.buildSpec.replace(buildSpec);
      b.previousBuild.replace(previousBuild);
      b.buildStepPlan.replace(buildStepPlan);
      b.conflictingOutputs.replace(conflictingOutputs);
      b.buildInputs = buildInputs;
      b.buildDirs.replace(buildDirs);
      b.buildFilters.replace(buildFilters);
    });
  }

  /// Reloads the build plan.
  ///
  /// Works just like a new load of the build plan, but sets
  /// `recentlyBootstrapped` to `false` to redo checks from bootstrapping.
  ///
  /// The caller must check `buildSpec.restartIsNeeded`.
  Future<BuildPlan> reload() async => BuildPlan.load(
    await BuildSpec.load(
      builderFactories: buildSpec.builderFactories,
      buildOptions: buildSpec.buildOptions.copyWith(
        buildDirs: buildDirs,
        buildFilters: buildFilters,
      ),
      testingOverrides: buildSpec.testingOverrides,
      recentlyBootstrapped: false,
    ),
  );
}
