// Copyright (c) 2025, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'package:build/build.dart' hide Builder;
import 'package:built_collection/built_collection.dart';
import 'package:built_value/built_value.dart';

import 'package:watcher/watcher.dart';

import '../build/asset_content.dart';
import '../build/build_state/build_state.dart';
import '../build/library_cycle_graph/phased_asset_deps.dart';
import '../constants.dart';
import '../exceptions.dart';
import '../io/asset_tracker.dart';
import '../io/generated_asset_hider.dart';
import '../io/reader_writer.dart';
import '../logging/build_log.dart';
import 'build_directory.dart';
import 'build_filter.dart';
import 'build_inputs.dart';
import 'build_spec.dart';
import 'build_step_plan.dart';
import 'previous_build.dart';

part 'build_plan.g.dart';

/// Options and derived configuration for a build.
abstract class BuildPlan implements Built<BuildPlan, BuildPlanBuilder> {
  BuildSpec get buildSpec;
  PreviousBuild get previousBuild;
  BuildStepPlan get buildStepPlan;
  ReaderWriter get readerWriter;

  /// Outputs that conflict with the current build setup and must be deleted.
  BuiltList<AssetId> get conflictingOutputs;

  /// Sources and changes to sources before the build.
  BuildInputs get buildInputs;

  /// Per-build build dirs, which can differ from the global option in
  /// `BuildOptions`.
  BuiltSet<BuildDirectory> get buildDirs;

  /// Per-build build filters, which can differ from the global option in
  /// `BuildOptions`.
  BuiltSet<BuildFilter> get buildFilters;

  BuildPlan._();
  factory BuildPlan([void Function(BuildPlanBuilder) updates]) = _$BuildPlan;

  /// Loads the build plan for [buildSpec].
  ///
  /// Loads information about the previous build as [previousBuild].
  ///
  /// Files that should be deleted before restarting or building are tracked.
  ///
  /// [buildInputs] are resolved.
  static Future<BuildPlan> load(BuildSpec buildSpec) async {
    final previousBuild = await PreviousBuild.load(buildSpec);
    final buildPackages = buildSpec.buildPackages;

    // Find sources on disk.
    final assetTracker = AssetTracker(
      buildSpec.readerWriter,
      buildPackages,
      buildSpec.buildConfigs,
    );
    final assetTrackerInputSources = await assetTracker.findInputSources();
    final cacheDirSources = await assetTracker.findCacheDirSources();

    final previousBuildState = previousBuild.buildState;
    if (previousBuildState == null) {
      // If there is no compatible previous build, compute inputs with files
      // that look like old generation outputs removed.

      final inputSources = assetTrackerInputSources.toSet();

      // Remove files from the incompatible build.
      inputSources.removeAll(previousBuild.incompatibleBuildOutputsToDelete);
      // The asset graph JSON is not an input.
      inputSources.remove(
        AssetId(buildPackages.outputRoot, assetGraphJsonPath),
      );

      // Remove from inputs files that will be generated by the current build.
      final declaredOutputs = BuildStepPlan.compute(
        buildPhases: buildSpec.buildPhases,
        placeholderIds: buildPackages.placeholderIds,
        sources: inputSources,
      ).declaredOutputs;
      inputSources.removeAll(declaredOutputs);

      return _createClean(
        buildSpec: buildSpec,
        previousBuild: previousBuild,
        buildDirs: buildSpec.buildOptions.buildDirs,
        buildFilters: buildSpec.buildOptions.buildFilters,
        filesToCheck: inputSources,
        assetTrackerInputSources: assetTrackerInputSources,
      );
    } else {
      // If there is a compatible previous build, check all previous build files
      // and all discovered files on disk.
      final filesToCheck = {
        ...assetTrackerInputSources,
        ...cacheDirSources,
        ...previousBuildState.sources,
        ...previousBuildState.actualOutputs,
      };

      final previousBuildStepPlan = BuildStepPlan.compute(
        buildPhases: buildSpec.buildPhases,
        placeholderIds: buildPackages.placeholderIds,
        sources: previousBuildState.sources,
      );

      return _createIncremental(
        buildSpec: buildSpec,
        previousBuild: previousBuild,
        previousBuildStepPlan: previousBuildStepPlan,
        buildDirs: buildSpec.buildOptions.buildDirs,
        buildFilters: buildSpec.buildOptions.buildFilters,
        filesToCheck: filesToCheck,
      );
    }
  }

  /// Returns a copy of the plan with [previousBuild] updated for the next
  /// incremental build.
  BuildPlan withCompatiblePreviousBuild({
    required BuildState previousBuildState,
    required PhasedAssetDeps previousPhasedAssetDeps,
  }) => rebuild(
    (b) => b
      ..previousBuild.replace(
        previousBuild.updateForNextBuild(
          previousPhasedAssetDeps: previousPhasedAssetDeps,
          previousBuildState: previousBuildState,
        ),
      )
      ..conflictingOutputs.clear(),
  );

  Future<BuildPlan> updateForFileChanges(Set<AssetId> filesToCheck) {
    final previousBuildState = previousBuild.buildState;
    if (previousBuildState == null) {
      return _createClean(
        buildSpec: buildSpec,
        previousBuild: previousBuild,
        buildDirs: buildDirs,
        buildFilters: buildFilters,
        filesToCheck: filesToCheck,
        // Updates are being made to a `BuildPlan` that didn't actually run.
        // That means the conflicting file check was already done when that
        // `BuildPlan` was created, don't repeat it.
        assetTrackerInputSources: null,
      );
    } else {
      return _createIncremental(
        buildSpec: buildSpec,
        previousBuild: previousBuild,
        previousBuildStepPlan: buildStepPlan,
        buildDirs: buildDirs,
        buildFilters: buildFilters,
        filesToCheck: filesToCheck,
      );
    }
  }

  /// Whether [phaseNumber] has different options to the previous build
  /// and must be fully rebuilt.
  bool phaseOptionsChanged(int phaseNumber) =>
      previousBuild.phaseOptionsChangedList[phaseNumber];

  /// Whether [actionNumber] has different options to the previous build
  /// and must be fully rebuilt.
  bool postBuildOptionsChanged(int actionNumber) =>
      previousBuild.postBuildOptionsChangedList[actionNumber];

  /// Creates a [BuildPlan] for a clean build.
  ///
  /// Pass [assetTrackerInputSources] to check if any files that builders
  /// will generate conflict with files already on disk. Conflicts in
  /// dependencies cause an exception to be thrown, conflicts in writable
  /// packages are added to [conflictingOutputs] so they will be deleted.
  static Future<BuildPlan> _createClean({
    required BuildSpec buildSpec,
    required PreviousBuild previousBuild,
    required BuiltSet<BuildDirectory> buildDirs,
    required BuiltSet<BuildFilter> buildFilters,
    required Set<AssetId> filesToCheck,
    Set<AssetId>? assetTrackerInputSources,
  }) async {
    final readerWriter = buildSpec.readerWriter.copyWith(
      generatedAssetHider: const NoopGeneratedAssetHider(),
    );
    final result = BuildInputsBuilder()..cleanBuild = true;

    for (final id in filesToCheck) {
      if (await readerWriter.canRead(id)) {
        result.sources.add(id);
      }
    }

    final buildStepPlan = BuildStepPlan.compute(
      buildPhases: buildSpec.buildPhases,
      placeholderIds: buildSpec.buildPackages.placeholderIds,
      sources: result.sources.build(),
    );

    final conflictingOutputs = <AssetId>{};
    final buildPackages = buildSpec.buildPackages;

    if (assetTrackerInputSources != null) {
      final conflictsInDeps = buildStepPlan.declaredOutputs
          .where((n) => !buildPackages.outputPackages.contains(n.package))
          .where(assetTrackerInputSources.contains)
          .toSet();
      if (conflictsInDeps.isNotEmpty) {
        buildLog.error(
          'There are existing files in dependencies which conflict '
          'with files that a Builder may produce. These must be removed or '
          'the Builders disabled before a build can continue: '
          '${conflictsInDeps.map((a) => a.uri).join('\n')}',
        );
        throw const CannotBuildException();
      }

      conflictingOutputs.addAll(
        buildStepPlan.declaredOutputs
            .where((n) => buildPackages.outputPackages.contains(n.package))
            .where(assetTrackerInputSources.contains)
            .toSet(),
      );
    }

    for (final id in result.sources.build()) {
      if (buildStepPlan.declaredOutputsOf(id).isNotEmpty) {
        try {
          result.sourceContents[id] = AssetContent.bytes(
            await readerWriter.readAsBytes(id),
          );
        } catch (_) {}
      }
    }

    return BuildPlan((b) {
      b.buildSpec.replace(buildSpec);
      b.previousBuild.replace(previousBuild);
      b.buildStepPlan.replace(buildStepPlan);
      b.readerWriter = readerWriter.copyWith(
        generatedAssetHider: buildSpec.testingOverrides.flattenOutput
            ? const NoopGeneratedAssetHider()
            : buildStepPlan,
      );
      b.conflictingOutputs.replace(conflictingOutputs);
      b.buildInputs.replace(result.build());
      b.buildDirs.replace(buildDirs);
      b.buildFilters.replace(buildFilters);
    });
  }

  /// Creates a [BuildPlan] for an incremental build.
  static Future<BuildPlan> _createIncremental({
    required BuildSpec buildSpec,
    required PreviousBuild previousBuild,
    required BuildStepPlan previousBuildStepPlan,
    required BuiltSet<BuildDirectory> buildDirs,
    required BuiltSet<BuildFilter> buildFilters,
    required Set<AssetId> filesToCheck,
  }) async {
    var readerWriter = buildSpec.readerWriter.copyWith(
      generatedAssetHider: buildSpec.testingOverrides.flattenOutput
          ? const NoopGeneratedAssetHider()
          : previousBuildStepPlan,
    );
    final buildInputs = BuildInputsBuilder()..cleanBuild = false;

    final newContents = <AssetId, AssetContent>{};
    final resolvedUpdates = <AssetId, ChangeType>{};
    final previousSources = <AssetId>{};

    final previousBuildState = previousBuild.buildState!;
    var buildStepPlan = previousBuildStepPlan;

    for (final id in filesToCheck) {
      final oldIsSource = previousBuildState.isSource(id);
      if (oldIsSource) {
        previousSources.add(id);
      }
      final oldExisted = previousBuildState.isFile(
        buildStepPlan: buildStepPlan,
        id: id,
      );
      final oldContent = oldIsSource
          ? previousBuildState.contentOfSource(id)
          : null;
      var exists = false;
      AssetContent? newContent;

      if (await readerWriter.canRead(id)) {
        exists = true;
        if (oldContent != null) {
          try {
            final bytes = await readerWriter.readAsBytes(id);
            newContent = AssetContent.bytes(bytes);
            newContents[id] = newContent;
          } catch (_) {
            exists = false;
          }
        }
      }

      if (oldExisted && !exists) {
        resolvedUpdates[id] = ChangeType.REMOVE;
        if (oldIsSource) {
          buildInputs.deletedSources.add(id);
        } else {
          buildInputs.deletedOutputs.add(id);
        }
      } else if (!oldExisted && exists) {
        buildInputs.addedSources.add(id);
        resolvedUpdates[id] = ChangeType.ADD;
      } else if (oldExisted &&
          oldContent != null &&
          exists &&
          oldContent.digest != newContent!.digest) {
        buildInputs.modifiedSources.add(id);
        resolvedUpdates[id] = ChangeType.MODIFY;
      }
    }

    buildInputs.sources.addAll(previousBuildState.sources);
    for (final entry in resolvedUpdates.entries) {
      final id = entry.key;
      switch (entry.value) {
        case ChangeType.ADD:
        case ChangeType.MODIFY:
          if (!previousBuildState.isSource(id) ||
              previousBuildState.isMissingSource(id)) {
            buildInputs.sources.add(id);
          }
        case ChangeType.REMOVE:
          if (previousBuildState.isSource(id)) {
            buildInputs.sources.remove(id);
          }
      }
    }

    for (final id in buildInputs.sources.build()) {
      if (newContents[id] != null) {
        buildInputs.sourceContents[id] = newContents[id]!;
      } else if (resolvedUpdates[id] == null) {
        if (previousBuildState.isSource(id)) {
          final content = previousBuildState.contentOfSource(id);
          if (content != null) {
            buildInputs.sourceContents[id] = content;
          }
        }
      }
    }

    buildStepPlan = BuildStepPlan.compute(
      buildPhases: buildSpec.buildPhases,
      placeholderIds: buildSpec.buildPackages.placeholderIds,
      sources: buildInputs.sources.build(),
    );

    for (final id in buildInputs.sources.build()) {
      if (buildInputs.sourceContents[id] == null &&
          buildStepPlan.declaredOutputsOf(id).isNotEmpty) {
        try {
          final bytes = await readerWriter.readAsBytes(id);
          buildInputs.sourceContents[id] = AssetContent.bytes(bytes);
        } catch (_) {}
      }
    }

    final deletedOutputs = previousBuildStepPlan
        .transitiveDeclaredOutputsOf(buildInputs.deletedSources.build())
        .toSet();
    buildInputs.deletedOutputs.addAll(deletedOutputs);

    readerWriter = readerWriter.copyWith(
      generatedAssetHider: buildSpec.testingOverrides.flattenOutput
          ? const NoopGeneratedAssetHider()
          : buildStepPlan,
    );
    for (final id in deletedOutputs) {
      await readerWriter.delete(id);
    }

    return BuildPlan((b) {
      b.buildSpec.replace(buildSpec);
      b.previousBuild.replace(previousBuild);
      b.buildStepPlan.replace(buildStepPlan);
      b.readerWriter = readerWriter;
      b.buildInputs = buildInputs;
      b.buildDirs.replace(buildDirs);
      b.buildFilters.replace(buildFilters);
    });
  }

  /// Reloads the build plan.
  ///
  /// Works just like a new load of the build plan, but sets
  /// `recentlyBootstrapped` to `false` to redo checks from bootstrapping.
  ///
  /// The caller must check `buildSpec.restartIsNeeded`.
  Future<BuildPlan> reload() async => BuildPlan.load(
    await BuildSpec.load(
      builderFactories: buildSpec.builderFactories,
      buildOptions: buildSpec.buildOptions.copyWith(
        buildDirs: buildDirs,
        buildFilters: buildFilters,
      ),
      testingOverrides: buildSpec.testingOverrides,
      recentlyBootstrapped: false,
    ),
  );
}
